package view;

import javax.swing.*;
import java.awt.*;

/**
 * Login Form to secure the Coffee Shop Management application.
 * Fully compatible with the NetBeans Matisse GUI editor design.
 */
public class LoginForm extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    public LoginForm() {
        initComponents();
        setupStyles();
    }

    private void setupStyles() {
        // Apply FlatLaf client properties for modern rounded styles & placeholders
        txtUsername.putClientProperty("JTextField.placeholderText", "Masukkan Username");
        txtUsername.putClientProperty("JTextField.showClearButton", true);
        
        txtPassword.putClientProperty("JTextField.placeholderText", "Masukkan Password");
        txtPassword.putClientProperty("JTextField.showClearButton", true);
        
        btnLogin.setBackground(new Color(98, 57, 53)); // Coffee brown theme
        btnLogin.setForeground(Color.WHITE);
        btnLogin.putClientProperty("JButton.buttonType", "roundRect");
        btnLogin.setFocusPainted(false);
        
        btnCancel.setBackground(new Color(117, 117, 117)); // Slate gray Cancel
        btnCancel.setForeground(Color.WHITE);
        btnCancel.putClientProperty("JButton.buttonType", "roundRect");
        btnCancel.setFocusPainted(false);
        
        headerPanel.setBackground(new Color(98, 57, 53));
        lblTitle.setForeground(Color.WHITE);
        lblSubtitle.setForeground(new Color(224, 224, 224));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login - Cafe Espresso Management");
        setResizable(false);
        getContentPane().setLayout(null);

        headerPanel.setBackground(new java.awt.Color(98, 57, 53));
        headerPanel.setLayout(null);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("☕ CAFE ESPRESSO");
        headerPanel.add(lblTitle);
        lblTitle.setBounds(10, 15, 380, 27);

        lblSubtitle.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblSubtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubtitle.setText("Management System Access Control");
        headerPanel.add(lblSubtitle);
        lblSubtitle.setBounds(10, 42, 380, 20);

        getContentPane().add(headerPanel);
        headerPanel.setBounds(0, 0, 400, 80);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel1.setText("Username:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 110, 80, 25);
        getContentPane().add(txtUsername);
        txtUsername.setBounds(120, 110, 240, 28);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel2.setText("Password:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 155, 80, 25);
        getContentPane().add(txtPassword);
        txtPassword.setBounds(120, 155, 240, 28);

        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(120, 210, 110, 35);

        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnCancel.setText("Batal");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel);
        btnCancel.setBounds(250, 210, 110, 35);

        setSize(new java.awt.Dimension(416, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String username = txtUsername.getText().trim();
        String password = new String(txtPassword.getPassword());

        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username dan password tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Basic credentials check (username: admin, password: admin)
        if (username.equals("admin") && password.equals("admin")) {
            JOptionPane.showMessageDialog(this, "Login berhasil! Selamat datang di Cafe Espresso.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            new MainDashboard().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Username atau password salah!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCancelActionPerformed

    public static void main(String args[]) {
        try {
            // Apply customized FlatLaf arc styling globally
            javax.swing.UIManager.put("Button.arc", 8);
            javax.swing.UIManager.put("Component.arc", 8);
            javax.swing.UIManager.put("TextComponent.arc", 8);
            javax.swing.UIManager.put("ScrollBar.thumbArc", 999);
            javax.swing.UIManager.put("ScrollBar.trackArc", 999);
            
            try {
                com.formdev.flatlaf.themes.FlatMacDarkLaf.setup();
            } catch (Exception e) {
                com.formdev.flatlaf.FlatDarkLaf.setup();
            }
        } catch (Exception ex) {
            System.err.println("Gagal menginisialisasi FlatLaf: " + ex.getMessage());
        }

        java.awt.EventQueue.invokeLater(() -> new LoginForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
